version: '3.7'
services:
  development:
    # container_name: nx-tutorial
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ../..:/host
      - ../../nx-tutorial:/nx-tutorial
    stdin_open: true
    tty: true
volumes:
  workspace:
